# Generated by Django 4.1.1 on 2022-11-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='user/images'),
        ),
    ]
